import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hodorak/core/models/shift.dart';
import 'package:hodorak/core/models/supabase_user.dart';
import 'package:hodorak/features/shift_management/data/repositories/shift_repository.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class AdminShiftState {
  final List<Shift> shifts;
  final List<SupabaseUser> employees;
  final bool isLoading;
  final String? error;
  final String? companyId;

  const AdminShiftState({
    this.shifts = const [],
    this.employees = const [],
    this.isLoading = false,
    this.error,
    this.companyId,
  });

  AdminShiftState copyWith({
    List<Shift>? shifts,
    List<SupabaseUser>? employees,
    bool? isLoading,
    String? error,
    String? companyId,
  }) {
    return AdminShiftState(
      shifts: shifts ?? this.shifts,
      employees: employees ?? this.employees,
      isLoading: isLoading ?? this.isLoading,
      error: error,
      companyId: companyId ?? this.companyId,
    );
  }
}

class AdminShiftViewModel extends Notifier<AdminShiftState> {
  final SupabaseClient _supabase = Supabase.instance.client;

  @override
  AdminShiftState build() {
    // Trigger initial load
    Future.microtask(() => loadData());
    return const AdminShiftState(isLoading: true);
  }

  Future<void> loadData() async {
    state = state.copyWith(isLoading: true, error: null);
    try {
      final repository = ref.read(shiftRepositoryProvider);
      final userId = _supabase.auth.currentUser?.id;
      if (userId == null) {
        state = state.copyWith(
          isLoading: false,
          error: 'User not authenticated',
        );
        return;
      }

      final companyId = await repository.getCompanyId(userId);
      if (companyId == null) {
        state = state.copyWith(
          isLoading: false,
          error: 'User not assigned to a company',
        );
        return;
      }

      final shifts = await repository.getCompanyShifts(companyId);
      final employees = await repository.getCompanyEmployees(companyId);

      state = state.copyWith(
        shifts: shifts,
        employees: employees,
        isLoading: false,
        companyId: companyId,
      );
    } catch (e) {
      state = state.copyWith(isLoading: false, error: e.toString());
    }
  }

  Future<bool> addShift({
    required String name,
    required TimeOfDay startTime,
    required TimeOfDay endTime,
    required int gracePeriodMinutes,
    required bool isOvernight,
  }) async {
    if (state.companyId == null) {
      state = state.copyWith(error: 'Company ID not found');
      return false;
    }

    state = state.copyWith(isLoading: true, error: null);
    try {
      final repository = ref.read(shiftRepositoryProvider);
      final shift = Shift(
        id: '', // Will be ignored/generated by DB
        companyId: state.companyId!,
        name: name,
        startTime: startTime,
        endTime: endTime,
        gracePeriodMinutes: gracePeriodMinutes,
        isOvernight: isOvernight,
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      await repository.addShift(shift);
      await loadData(); // Reload data
      return true;
    } catch (e) {
      state = state.copyWith(isLoading: false, error: e.toString());
      return false;
    }
  }

  Future<bool> assignEmployeeToShift(String shiftId, String userId) async {
    try {
      final repository = ref.read(shiftRepositoryProvider);
      await repository.assignEmployeeToShift(shiftId, userId);
      return true;
    } catch (e) {
      state = state.copyWith(error: e.toString());
      return false;
    }
  }
}

final adminShiftViewModelProvider =
    NotifierProvider<AdminShiftViewModel, AdminShiftState>(
      AdminShiftViewModel.new,
    );
