// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXeT5zvrv9vuaZXDRX0OH9ejW0UZWng5I',
    appId: '1:436763573657:web:24a9190a0b304ae785a708',
    messagingSenderId: '436763573657',
    projectId: 'odoo-attendance-f1058',
    authDomain: 'odoo-attendance-f1058.firebaseapp.com',
    storageBucket: 'odoo-attendance-f1058.firebasestorage.app',
    measurementId: 'G-6V7Q1K3VN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9XuCpFtZohlVTwGsfwGAoOwpVow1zPPU',
    appId: '1:436763573657:android:9c6397628bad78cb85a708',
    messagingSenderId: '436763573657',
    projectId: 'odoo-attendance-f1058',
    storageBucket: 'odoo-attendance-f1058.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRLxL-OBdBh9TE8yjsXJxqePdWd4GuDlg',
    appId: '1:436763573657:ios:d5fea227e1aff39b85a708',
    messagingSenderId: '436763573657',
    projectId: 'odoo-attendance-f1058',
    storageBucket: 'odoo-attendance-f1058.firebasestorage.app',
    iosBundleId: 'com.example.hodorak',
  );
}
