# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Android firebase Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build apk --release"
    firebase_app_distribution(
    app: "1:436763573657:android:9c6397628bad78cb85a708",
    firebase_cli_token:"1//03z_QTKSozgf-CgYIARAAGAMSNwF-L9IrYyivVRmEaqAC88nvVWenKUsEjUCgtv-_DGTM91ZicgCenwCys1k1xi41VQIRNAcNprI",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
    release_notes: "New build is available for testing",
    testers: "heshamhamdan512@gmail.com"
  )
  end

end
